tmp: bundle target before storing (+ early out in pipeline)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -90,151 +90,155 @@ jobs:
           name: Fix timestamps
           command: find target/universal/stage -exec touch -t 197001010000 {} +
 
+      - run:
+          name: Bundle target/universal/stage
+          command: tar -czvf target.tar target/universal/stage
+
       - store_artifacts:
           path: target/universal/stage
 
-      - run:
-          name: Checksum App Dirs
-          command: find app webknossos-datastore/app webknossos-tracingstore/app -type f -exec md5sum {} \; | sort -k 2 | md5sum > app_checksum.txt
+      # - run:
+      #     name: Checksum App Dirs
+      #     command: find app webknossos-datastore/app webknossos-tracingstore/app -type f -exec md5sum {} \; | sort -k 2 | md5sum > app_checksum.txt
 
-      - save_cache:
-          name: Save target cache
-          key: target-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ checksum "app_checksum.txt" }}
-          paths:
-            - "project/target"
-            - "target"
+      # - save_cache:
+      #     name: Save target cache
+      #     key: target-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ checksum "app_checksum.txt" }}
+      #     paths:
+      #       - "project/target"
+      #       - "target"
 
-      - save_cache:
-          name: Save sbt cache
-          key: sbt-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "project/Dependencies.scala" }}
-          paths:
-            - "~/.ivy2"
-            - "~/.cache/coursier"
+      # - save_cache:
+      #     name: Save sbt cache
+      #     key: sbt-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "project/Dependencies.scala" }}
+      #     paths:
+      #       - "~/.ivy2"
+      #       - "~/.cache/coursier"
 
-      - save_cache:
-          name: Save yarn cache
-          key: yarn-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "yarn.lock" }}
-          paths:
-            - "~/.cache/yarn"
+      # - save_cache:
+      #     name: Save yarn cache
+      #     key: yarn-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "yarn.lock" }}
+      #     paths:
+      #       - "~/.cache/yarn"
 
-      - run:
-          name: Build webknossos docker image
-          command: |
-            docker pull scalableminds/webknossos:$NORMALIZED_BRANCH || true
-            DEV_CACHE=$NORMALIZED_BRANCH docker-compose build --pull webknossos
+      # - run:
+      #     name: Build webknossos docker image
+      #     command: |
+      #       docker pull scalableminds/webknossos:$NORMALIZED_BRANCH || true
+      #       DEV_CACHE=$NORMALIZED_BRANCH docker-compose build --pull webknossos
 
-      - run:
-          name: Build webknossos-datastore docker image
-          command: docker-compose build --pull webknossos-datastore
+      # - run:
+      #     name: Build webknossos-datastore docker image
+      #     command: docker-compose build --pull webknossos-datastore
 
-      - run:
-          name: Build webknossos-tracingstore docker image
-          command: docker-compose build --pull webknossos-tracingstore
+      # - run:
+      #     name: Build webknossos-tracingstore docker image
+      #     command: docker-compose build --pull webknossos-tracingstore
 
-      - run:
-          name: Lint frontend code and check formatting
-          command: |
-            .circleci/not-on-master.sh docker-compose run base bash -c "yarn run check-frontend"
-      - run:
-          name: Check for cyclic dependencies in front-end
-          command: |
-            .circleci/not-on-master.sh docker-compose run base yarn check-cyclic-dependencies
-      - run:
-          name: Run frontend tests
-          command: |
-            .circleci/not-on-master.sh docker-compose run base yarn test-verbose
-      - run:
-          name: Lint backend code and check formatting
-          command: |
-            .circleci/not-on-master.sh docker-compose run backend-lint-format
-      - run:
-          name: Run backend tests
-          command: |
-            .circleci/not-on-master.sh docker-compose run backend-tests
-      - run:
-          name: Run end-to-end tests
-          command: |
-            for i in {1..3}; do # retry
-              .circleci/not-on-master.sh docker-compose run e2e-tests && s=0 && break || s=$?
-            done
-            (exit $s)
-      - run:
-          name: Validate frontend types
-          command: |
-            .circleci/not-on-master.sh docker-compose run base yarn typecheck
-      - run:
-          name: Start webknossos, datastore and tracingstore
-          command: docker-compose up -d webknossos && docker-compose up -d webknossos-datastore && docker-compose up -d webknossos-tracingstore
+      # - run:
+      #     name: Lint frontend code and check formatting
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run base bash -c "yarn run check-frontend"
+      # - run:
+      #     name: Check for cyclic dependencies in front-end
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run base yarn check-cyclic-dependencies
+      # - run:
+      #     name: Run frontend tests
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run base yarn test-verbose
+      # - run:
+      #     name: Lint backend code and check formatting
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run backend-lint-format
+      # - run:
+      #     name: Run backend tests
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run backend-tests
+      # - run:
+      #     name: Run end-to-end tests
+      #     command: |
+      #       for i in {1..3}; do # retry
+      #         .circleci/not-on-master.sh docker-compose run e2e-tests && s=0 && break || s=$?
+      #       done
+      #       (exit $s)
+      # - run:
+      #     name: Validate frontend types
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run base yarn typecheck
+      # - run:
+      #     name: Start webknossos, datastore and tracingstore
+      #     command: docker-compose up -d webknossos && docker-compose up -d webknossos-datastore && docker-compose up -d webknossos-tracingstore
 
-      - run:
-          name: Run webknossos smoke test
-          command: |
-            for i in {1..20}; do # retry
-              curl --fail -v http://localhost:9000/api/health && s=0 && break || s=$?
-              sleep 5
-            done
-            (exit $s)
+      # - run:
+      #     name: Run webknossos smoke test
+      #     command: |
+      #       for i in {1..20}; do # retry
+      #         curl --fail -v http://localhost:9000/api/health && s=0 && break || s=$?
+      #         sleep 5
+      #       done
+      #       (exit $s)
 
-      - run:
-          name: Run webknossos-datastore smoke test
-          command: |
-            for i in {1..20}; do # retry
-              curl --fail -v http://localhost:9090/data/health && s=0 && break || s=$?
-              sleep 5
-            done
-            (exit $s)
+      # - run:
+      #     name: Run webknossos-datastore smoke test
+      #     command: |
+      #       for i in {1..20}; do # retry
+      #         curl --fail -v http://localhost:9090/data/health && s=0 && break || s=$?
+      #         sleep 5
+      #       done
+      #       (exit $s)
 
-      - run:
-          name: Run webknossos-tracingstore smoke test
-          command: |
-            for i in {1..20}; do # retry
-              curl --fail -v http://localhost:9050/tracings/health && s=0 && break || s=$?
-              sleep 5
-            done
-            (exit $s)
-      - run:
-          name: Stop webknossos, datastore and tracingstore
-          command: docker-compose down --volumes --remove-orphans
+      # - run:
+      #     name: Run webknossos-tracingstore smoke test
+      #     command: |
+      #       for i in {1..20}; do # retry
+      #         curl --fail -v http://localhost:9050/tracings/health && s=0 && break || s=$?
+      #         sleep 5
+      #       done
+      #       (exit $s)
+      # - run:
+      #     name: Stop webknossos, datastore and tracingstore
+      #     command: docker-compose down --volumes --remove-orphans
 
-      - run:
-          name: Push docker images
-          command: |
-            function retry() {
-              for i in {1..5}; do
-                "$@" && s=0 && break || s=$?
-                sleep 10
-              done
-              return $s
-            }
-            retry sh -c 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
-            retry docker-compose push webknossos
-            retry docker-compose push webknossos-datastore
-            retry docker-compose push webknossos-tracingstore
-            if [ -n "$CIRCLE_BRANCH" ]; then
-              docker tag \
-                scalableminds/webknossos:${DOCKER_TAG} \
-                scalableminds/webknossos:${NORMALIZED_BRANCH}
-              retry docker push scalableminds/webknossos:${NORMALIZED_BRANCH}
-              docker tag \
-                scalableminds/webknossos-datastore:${DOCKER_TAG} \
-                scalableminds/webknossos-datastore:${NORMALIZED_BRANCH}
-              retry docker push scalableminds/webknossos-datastore:${NORMALIZED_BRANCH}
-              docker tag \
-                scalableminds/webknossos-tracingstore:${DOCKER_TAG} \
-                scalableminds/webknossos-tracingstore:${NORMALIZED_BRANCH}
-              retry docker push scalableminds/webknossos-tracingstore:${NORMALIZED_BRANCH}
-              docker tag \
-                scalableminds/webknossos-dev \
-                scalableminds/webknossos-dev:${NORMALIZED_BRANCH}
-              retry docker push scalableminds/webknossos-dev:${NORMALIZED_BRANCH}
-            fi
-            docker logout
-      - run:
-          name: Report coverage
-          command: .circleci/not-on-master.sh docker-compose run base yarn coverage || true
-      - run:
-          name: Send Slack notification (master only)
-          command: .circleci/slack-notification.sh
+      # - run:
+      #     name: Push docker images
+      #     command: |
+      #       function retry() {
+      #         for i in {1..5}; do
+      #           "$@" && s=0 && break || s=$?
+      #           sleep 10
+      #         done
+      #         return $s
+      #       }
+      #       retry sh -c 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
+      #       retry docker-compose push webknossos
+      #       retry docker-compose push webknossos-datastore
+      #       retry docker-compose push webknossos-tracingstore
+      #       if [ -n "$CIRCLE_BRANCH" ]; then
+      #         docker tag \
+      #           scalableminds/webknossos:${DOCKER_TAG} \
+      #           scalableminds/webknossos:${NORMALIZED_BRANCH}
+      #         retry docker push scalableminds/webknossos:${NORMALIZED_BRANCH}
+      #         docker tag \
+      #           scalableminds/webknossos-datastore:${DOCKER_TAG} \
+      #           scalableminds/webknossos-datastore:${NORMALIZED_BRANCH}
+      #         retry docker push scalableminds/webknossos-datastore:${NORMALIZED_BRANCH}
+      #         docker tag \
+      #           scalableminds/webknossos-tracingstore:${DOCKER_TAG} \
+      #           scalableminds/webknossos-tracingstore:${NORMALIZED_BRANCH}
+      #         retry docker push scalableminds/webknossos-tracingstore:${NORMALIZED_BRANCH}
+      #         docker tag \
+      #           scalableminds/webknossos-dev \
+      #           scalableminds/webknossos-dev:${NORMALIZED_BRANCH}
+      #         retry docker push scalableminds/webknossos-dev:${NORMALIZED_BRANCH}
+      #       fi
+      #       docker logout
+      # - run:
+      #     name: Report coverage
+      #     command: .circleci/not-on-master.sh docker-compose run base yarn coverage || true
+      # - run:
+      #     name: Send Slack notification (master only)
+      #     command: .circleci/slack-notification.sh
 
   nightly:
     docker:
