run only on master, re-add other build steps

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,6 +10,212 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Build webknossos-dev docker image
+          command: |
+            docker pull scalableminds/webknossos-dev:$CIRCLE_BRANCH || true
+            DEV_CACHE=$CIRCLE_BRANCH docker-compose build base
+      - run:
+          name: Prepare dependency folders
+          command: mkdir -p project/target target ~/.ivy2 ~/.cache/coursier ~/.cache/yarn
+      - restore_cache:
+          name: Restore target cache
+          keys:
+            - target-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
+            - target-cache-{{ checksum ".circleci/cache_version" }}-master
+      - restore_cache:
+          name: Restore sbt cache
+          keys:
+            - sbt-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "project/Dependencies.scala" }}
+            - sbt-cache-{{ checksum ".circleci/cache_version" }}-
+      - restore_cache:
+          name: Restore yarn cache
+          keys:
+            - yarn-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "yarn.lock" }}
+            - yarn-cache-{{ checksum ".circleci/cache_version" }}-
+      - run:
+          name: Assert unique evolution numbers
+          command: tools/postgres/assert_unique_evolution_numbers.sh
+      - run:
+          name: Install frontend dependencies
+          command: docker-compose run base yarn install --frozen-lockfile
+      - restore_cache:
+          name: Restore webpack-uglifyjs cache
+          keys:
+            - webpack-uglifyjs-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}
+            - webpack-uglifyjs-cache-{{ checksum ".circleci/cache_version" }}-master
+      - run:
+          name: Assert schema.sql and evolutions are equal
+          command: |
+            docker-compose up -d postgres
+            sleep 3
+            docker-compose run compile tools/postgres/diff_schema.js tools/postgres/schema.sql "conf/evolutions/*.sql"
+      - run:
+          name: Build frontend documentation
+          command: docker-compose run base yarn run docs
+      - run:
+          name: Build webknossos (sbt and webpack)
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+              docker-compose run compile sbt clean compile stage
+            else
+              docker-compose run compile sbt compile stage
+            fi
+      - run:
+          name: Build webknossos-datastore (sbt)
+          command: docker-compose run base sbt "project webknossosDatastore" compile stage
+
+      - run:
+          name: Build webknossos-tracingstore (sbt)
+          command: docker-compose run base sbt "project webknossosTracingstore" compile stage
+
+      - save_cache:
+          name: Save target cache
+          key: target-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
+          paths:
+            - "project/target"
+            - "target"
+
+      - save_cache:
+          name: Save sbt cache
+          key: sbt-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "project/Dependencies.scala" }}
+          paths:
+            - "~/.ivy2"
+            - "~/.cache/coursier"
+
+      - save_cache:
+          name: Save yarn cache
+          key: yarn-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "yarn.lock" }}
+          paths:
+            - "~/.cache/yarn"
+
+      - save_cache:
+          name: Save webpack-uglifyjs cache
+          key: webpack-uglifyjs-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
+          paths:
+            - "node_modules/.cache/uglifyjs-webpack-plugin"
+
+      - run:
+          name: Build webknossos docker image
+          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose build --pull webknossos
+
+      - run:
+          name: Build webknossos-datastore docker image
+          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose build --pull webknossos-datastore
+
+      - run:
+          name: Build webknossos-tracingstore docker image
+          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose build --pull webknossos-tracingstore
+
+      - run:
+          name: Lint frontend code
+          command: |
+            .circleci/not-on-master.sh docker-compose run base bash -c "yarn run lint && yarn run am-i-pretty"
+      - run:
+          name: Run frontend tests
+          command: |
+            .circleci/not-on-master.sh docker-compose run base yarn test-verbose
+      - run:
+          name: Lint backend code
+          command: |
+            .circleci/not-on-master.sh docker-compose run backend-lint-format
+      - run:
+          name: Run backend tests
+          command: |
+            .circleci/not-on-master.sh docker-compose run backend-tests
+      - run:
+          name: Run end-to-end tests
+          command: |
+            for i in {1..3}; do # retry
+              .circleci/not-on-master.sh docker-compose run e2e-tests && s=0 && break || s=$?
+            done
+            (exit $s)
+      - run:
+          name: Validate frontend types with flow
+          command: |
+            .circleci/not-on-master.sh docker-compose run base yarn flow
+      - run:
+          name: Start webknossos
+          background: true
+          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos
+      - run:
+          name: Run webknossos smoke test
+          command: |
+            sleep 10
+            ./test/infrastructure/deployment.bash
+      - run:
+          name: Stop webknossos
+          command: docker-compose down --volumes --remove-orphans
+
+      - run:
+          name: Start webknossos-datastore
+          background: true
+          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos-datastore
+      - run:
+          name: Run webknossos-datastore smoke test
+          command: |
+            sleep 10
+            curl --fail --retry 3 --max-time 15 -v http://localhost:9090/data/health
+      - run:
+          name: Stop webknossos-datastore
+          command: docker-compose down --volumes --remove-orphans
+
+      - run:
+          name: Start webknossos-tracingstore
+          background: true
+          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos-tracingstore
+      - run:
+          name: Run webknossos-tracingstore smoke test
+          command: |
+            sleep 10
+            curl --fail --retry 3 --max-time 15 -v http://localhost:9050/tracings/health
+      - run:
+          name: Stop webknossos-tracingstore
+          command: docker-compose down --volumes --remove-orphans
+
+      - run:
+          name: Push docker images
+          command: |
+            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
+            if [ -n "$CIRCLE_TAG" ]; then
+              docker tag \
+                scalableminds/webknossos:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
+                scalableminds/webknossos:$CIRCLE_TAG
+              docker push scalableminds/webknossos:$CIRCLE_TAG
+              docker tag \
+                scalableminds/webknossos-datastore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
+                scalableminds/webknossos-datastore:$CIRCLE_TAG
+              docker push scalableminds/webknossos-datastore:$CIRCLE_TAG
+              docker tag \
+                scalableminds/webknossos-tracingstore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
+                scalableminds/webknossos-tracingstore:$CIRCLE_TAG
+              docker push scalableminds/webknossos-tracingstore:$CIRCLE_TAG
+            fi
+            if [ -n "$CIRCLE_BRANCH" ]; then
+              docker tag \
+                scalableminds/webknossos:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
+                scalableminds/webknossos:${CIRCLE_BRANCH}
+              docker push scalableminds/webknossos:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
+              docker push scalableminds/webknossos:${CIRCLE_BRANCH}
+              docker tag \
+                scalableminds/webknossos-datastore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
+                scalableminds/webknossos-datastore:${CIRCLE_BRANCH}
+              docker push scalableminds/webknossos-datastore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
+              docker push scalableminds/webknossos-datastore:${CIRCLE_BRANCH}
+              docker tag \
+                scalableminds/webknossos-tracingstore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} \
+                scalableminds/webknossos-tracingstore:${CIRCLE_BRANCH}
+              docker push scalableminds/webknossos-tracingstore:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
+              docker push scalableminds/webknossos-tracingstore:${CIRCLE_BRANCH}
+              docker tag \
+                scalableminds/webknossos-dev \
+                scalableminds/webknossos-dev:$CIRCLE_BRANCH
+              docker push scalableminds/webknossos-dev:$CIRCLE_BRANCH
+            fi
+            docker logout
+      - run:
+          name: Report coverage
+          command: .circleci/not-on-master.sh docker-compose run base yarn coverage
+      - run:
           name: Send Slack notification (master only)
           command: .circleci/slack-notification.sh
 
