disable some ci checks for speed up

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -72,31 +72,31 @@ jobs:
           name: Build webknossos-tracingstore (sbt)
           command: docker-compose run base sbt "project webknossosTracingstore" compile stage
 
-      - save_cache:
-          name: Save target cache
-          key: target-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
-          paths:
-            - "project/target"
-            - "target"
+      # - save_cache:
+      #     name: Save target cache
+      #     key: target-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
+      #     paths:
+      #       - "project/target"
+      #       - "target"
 
-      - save_cache:
-          name: Save sbt cache
-          key: sbt-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "project/Dependencies.scala" }}
-          paths:
-            - "~/.ivy2"
-            - "~/.cache/coursier"
+      # - save_cache:
+      #     name: Save sbt cache
+      #     key: sbt-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "project/Dependencies.scala" }}
+      #     paths:
+      #       - "~/.ivy2"
+      #       - "~/.cache/coursier"
 
-      - save_cache:
-          name: Save yarn cache
-          key: yarn-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "yarn.lock" }}
-          paths:
-            - "~/.cache/yarn"
+      # - save_cache:
+      #     name: Save yarn cache
+      #     key: yarn-cache-{{ checksum ".circleci/cache_version" }}-{{ checksum "yarn.lock" }}
+      #     paths:
+      #       - "~/.cache/yarn"
 
-      - save_cache:
-          name: Save webpack-uglifyjs cache
-          key: webpack-uglifyjs-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
-          paths:
-            - "node_modules/.cache/uglifyjs-webpack-plugin"
+      # - save_cache:
+      #     name: Save webpack-uglifyjs cache
+      #     key: webpack-uglifyjs-cache-{{ checksum ".circleci/cache_version" }}-{{ .Branch }}-{{ .Revision }}
+      #     paths:
+      #       - "node_modules/.cache/uglifyjs-webpack-plugin"
 
       - run:
           name: Build webknossos docker image
@@ -110,74 +110,74 @@ jobs:
           name: Build webknossos-tracingstore docker image
           command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose build --pull webknossos-tracingstore
 
-      - run:
-          name: Lint frontend code
-          command: |
-            .circleci/not-on-master.sh docker-compose run base bash -c "yarn run lint && yarn run am-i-pretty"
-      - run:
-          name: Run frontend tests
-          command: |
-            .circleci/not-on-master.sh docker-compose run base yarn test-verbose
-      - run:
-          name: Lint backend code
-          command: |
-            .circleci/not-on-master.sh docker-compose run backend-lint-format
-      - run:
-          name: Run backend tests
-          command: |
-            .circleci/not-on-master.sh docker-compose run backend-tests
-      - run:
-          name: Run end-to-end tests
-          command: |
-            for i in {1..3}; do # retry
-              .circleci/not-on-master.sh docker-compose run e2e-tests && s=0 && break || s=$?
-            done
-            (exit $s)
-      - run:
-          name: Validate frontend types with flow
-          command: |
-            .circleci/not-on-master.sh docker-compose run base yarn flow
-      - run:
-          name: Start webknossos
-          background: true
-          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos
-      - run:
-          name: Run webknossos smoke test
-          command: |
-            for i in {1..10}; do # retry
-              sleep 10
-              curl --fail -v http://localhost:9000/api/health && s=0 && break || s=$?
-            done
-            (exit $s)
-      - run:
-          name: Stop webknossos
-          command: docker-compose down --volumes --remove-orphans
+      # - run:
+      #     name: Lint frontend code
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run base bash -c "yarn run lint && yarn run am-i-pretty"
+      # - run:
+      #     name: Run frontend tests
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run base yarn test-verbose
+      # - run:
+      #     name: Lint backend code
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run backend-lint-format
+      # - run:
+      #     name: Run backend tests
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run backend-tests
+      # - run:
+      #     name: Run end-to-end tests
+      #     command: |
+      #       for i in {1..3}; do # retry
+      #         .circleci/not-on-master.sh docker-compose run e2e-tests && s=0 && break || s=$?
+      #       done
+      #       (exit $s)
+      # - run:
+      #     name: Validate frontend types with flow
+      #     command: |
+      #       .circleci/not-on-master.sh docker-compose run base yarn flow
+      # - run:
+      #     name: Start webknossos
+      #     background: true
+      #     command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos
+      # - run:
+      #     name: Run webknossos smoke test
+      #     command: |
+      #       for i in {1..10}; do # retry
+      #         sleep 10
+      #         curl --fail -v http://localhost:9000/api/health && s=0 && break || s=$?
+      #       done
+      #       (exit $s)
+      # - run:
+      #     name: Stop webknossos
+      #     command: docker-compose down --volumes --remove-orphans
 
-      - run:
-          name: Start webknossos-datastore
-          background: true
-          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos-datastore
-      - run:
-          name: Run webknossos-datastore smoke test
-          command: |
-            sleep 10
-            curl --fail --retry 3 --max-time 15 -v http://localhost:9090/data/health
-      - run:
-          name: Stop webknossos-datastore
-          command: docker-compose down --volumes --remove-orphans
+      # - run:
+      #     name: Start webknossos-datastore
+      #     background: true
+      #     command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos-datastore
+      # - run:
+      #     name: Run webknossos-datastore smoke test
+      #     command: |
+      #       sleep 10
+      #       curl --fail --retry 3 --max-time 15 -v http://localhost:9090/data/health
+      # - run:
+      #     name: Stop webknossos-datastore
+      #     command: docker-compose down --volumes --remove-orphans
 
-      - run:
-          name: Start webknossos-tracingstore
-          background: true
-          command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos-tracingstore
-      - run:
-          name: Run webknossos-tracingstore smoke test
-          command: |
-            sleep 30
-            curl --fail --retry 3 --max-time 15 -v http://localhost:9050/tracings/health
-      - run:
-          name: Stop webknossos-tracingstore
-          command: docker-compose down --volumes --remove-orphans
+      # - run:
+      #     name: Start webknossos-tracingstore
+      #     background: true
+      #     command: DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up webknossos-tracingstore
+      # - run:
+      #     name: Run webknossos-tracingstore smoke test
+      #     command: |
+      #       sleep 30
+      #       curl --fail --retry 3 --max-time 15 -v http://localhost:9050/tracings/health
+      # - run:
+      #     name: Stop webknossos-tracingstore
+      #     command: docker-compose down --volumes --remove-orphans
 
       - run:
           name: Push docker images
