don't repeat basic testing for builds in master since they were already run in the corresponding PR

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -84,24 +84,47 @@ jobs:
 
       - run:
           name: Lint frontend code
-          command: docker-compose run base bash -c "yarn run lint && yarn run am-i-pretty"
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+              echo "Skipping this step on master..."
+            else
+              docker-compose run base bash -c "yarn run lint && yarn run am-i-pretty"
+            fi
       - run:
           name: Run frontend tests
-          command: docker-compose run base yarn test-verbose
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+              echo "Skipping this step on master..."
+            else
+              docker-compose run base yarn test-verbose
+            fi
       - run:
           name: Run backend tests
-          command: docker-compose run backend-tests
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+              echo "Skipping this step on master..."
+            else
+              docker-compose run backend-tests
+            fi
       - run:
           name: Run end-to-end tests
           command: |
-            for i in {1..3}; do # retry
-              docker-compose run e2e-tests && s=0 && break || s=$?
-            done
-            (exit $s)
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+              echo "Skipping this step on master..."
+            else
+              for i in {1..3}; do # retry
+                docker-compose run e2e-tests && s=0 && break || s=$?
+              done
+              (exit $s)
+            fi
       - run:
           name: Validate frontend types with flow
-          command: docker-compose run base yarn flow
-
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+              echo "Skipping this step on master..."
+            else
+              docker-compose run base yarn flow
+            fi
       - run:
           name: Start webknossos
           background: true
