use not-on-master.sh for e2e step

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -125,14 +125,10 @@ jobs:
       - run:
           name: Run end-to-end tests
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              echo "Skipping this step on master..."
-            else
-              for i in {1..3}; do # retry
-                docker-compose run e2e-tests && s=0 && break || s=$?
-              done
-              (exit $s)
-            fi
+            for i in {1..3}; do # retry
+              .circleci/not-on-master.sh docker-compose run e2e-tests && s=0 && break || s=$?
+            done
+            (exit $s)
       - run:
           name: Validate frontend types with flow
           command: |
